version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel_network
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom config file
        networks:
            - laravel_network
        depends_on:
            - app


networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
